# Generated by Django 3.0.3 on 2021-12-09 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0081_auto_20211115_0729'),
        ('owners', '0004_authenticateduser_random_auth_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinleClinicBestArticleText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_clinic_world_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('clinic_world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.BasicClinic')),
            ],
        ),
    ]
