# Generated by Django 3.0.3 on 2021-12-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0081_auto_20211115_0729'),
        ('owners', '0005_sinleclinicbestarticletext'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SinleClinicBestArticleText',
            new_name='SingleClinicBestArticleText',
        ),
    ]
