# Generated by Django 3.0.3 on 2021-12-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0008_auto_20211209_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleclinicbestarticletext',
            name='user',
        ),
    ]
