# Generated by Django 3.0.3 on 2021-12-11 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owners', '0009_remove_singleclinicbestarticletext_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleclinicbestarticletext',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
