# Generated by Django 3.0.3 on 2021-12-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0010_singleclinicbestarticletext_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleclinicbestarticletext',
            name='best_clinic_world_activated',
            field=models.BooleanField(default=False),
        ),
    ]
