# Generated by Django 3.0.3 on 2021-12-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0081_auto_20211115_0729'),
        ('owners', '0011_singleclinicbestarticletext_best_clinic_world_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleclinicbestarticletext',
            name='clinic_world',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.BasicClinic'),
        ),
    ]
