# Generated by Django 3.2.11 on 2022-02-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0013_auto_20211213_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticateduser',
            name='register_as_clinic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authenticateduser',
            name='register_as_coach',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
