# Generated by Django 3.0.3 on 2021-04-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20201002_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='stripeid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
