# Generated by Django 3.0.3 on 2021-02-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0040_auto_20201218_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestauthorname', models.CharField(max_length=40)),
                ('guestauthorlastname', models.CharField(max_length=40)),
                ('guestauthorpic', models.ImageField(blank=True, null=True, upload_to='guestBloggingPhotos')),
                ('guestauthorpicdelete', models.BooleanField(blank=True, default=False, null=True)),
                ('guestauthordescription', models.TextField()),
                ('guestlinkedinurl', models.URLField(blank=True, null=True)),
                ('guestfacebookurl', models.URLField(blank=True, null=True)),
                ('guesttwitterurl', models.URLField(blank=True, null=True)),
                ('guestadditionalurl', models.URLField(blank=True, null=True)),
                ('guestauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.BasicClinic')),
            ],
        ),
        migrations.CreateModel(
            name='GuestBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestblogtitle', models.CharField(max_length=200)),
                ('guestblogdescription', models.TextField()),
                ('guestblogpicblogmain', models.ImageField(upload_to='guestBloggingPhotos')),
                ('guestblogpicblog1', models.ImageField(blank=True, null=True, upload_to='guestBloggingPhotos')),
                ('guestblogpicblog2', models.ImageField(blank=True, null=True, upload_to='guestBloggingPhotos')),
                ('guestblogpicblog3', models.ImageField(blank=True, null=True, upload_to='guestBloggingPhotos')),
                ('guestblogtag', models.CharField(choices=[('IVF-Abroad', 'IVF-Abroad'), ('IVF Packages', 'IVF Packages'), ('IVF Costs', 'IVF Costs')], max_length=40, null=True)),
                ('guestblogcreatedat', models.DateTimeField(auto_now_add=True)),
                ('guestbloglastmodified', models.DateTimeField(auto_now=True)),
                ('guestblogblogurl', models.URLField()),
                ('guestblogminuteread', models.IntegerField(blank=True, null=True)),
                ('guestblogactive', models.BooleanField(default=False)),
                ('guestblogauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestblogging.GuestAuthor')),
            ],
        ),
    ]
