# Generated by Django 3.0.3 on 2021-03-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestblogging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestblog',
            name='guestblogcity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guestblog',
            name='guestblogcountry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guestblog',
            name='guestblogregion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guestblog',
            name='guestblogblogurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
