# Generated by Django 3.0.3 on 2021-11-15 07:29

import clinic.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestblogging', '0002_auto_20210302_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestblog',
            name='guestblogpicblog1',
            field=models.ImageField(blank=True, null=True, upload_to='guestBloggingPhotos', validators=[clinic.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='guestblog',
            name='guestblogpicblog2',
            field=models.ImageField(blank=True, null=True, upload_to='guestBloggingPhotos', validators=[clinic.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='guestblog',
            name='guestblogpicblog3',
            field=models.ImageField(blank=True, null=True, upload_to='guestBloggingPhotos', validators=[clinic.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='guestblog',
            name='guestblogpicblogmain',
            field=models.ImageField(upload_to='guestBloggingPhotos', validators=[clinic.validators.validate_file_size]),
        ),
    ]
