# Generated by Django 3.0.3 on 2020-06-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0028_auto_20200518_1633'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='packageClinics',
            field=models.ManyToManyField(blank=True, related_name='packageClinics', to='clinic.BasicClinic'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='packageClinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageClinic', to='clinic.BasicClinic'),
        ),
    ]
