# Generated by Django 3.0.3 on 2020-07-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20200625_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='packagescategory',
            field=models.CharField(choices=[('All packages', 'All packages'), ('IVF packages', 'IVF packages'), ('Egg Donation', 'Egg Donation'), ('Embryo Donation', 'Embryo Donation')], default='All packages', max_length=40, null=True),
        ),
    ]
