# Generated by Django 3.0.3 on 2020-08-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0032_auto_20200728_0340'),
        ('packages', '0003_auto_20200715_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruePackages',
            fields=[
                ('basicclinic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clinic.BasicClinic')),
                ('Truepackagetitle', models.CharField(blank=True, max_length=30, null=True)),
            ],
            bases=('clinic.basicclinic',),
        ),
    ]
