# Generated by Django 3.0.3 on 2020-08-14 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0032_auto_20200728_0340'),
        ('packages', '0004_truepackages'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='packageState',
            field=models.ForeignKey(blank=True, db_column='clinicState', null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.BasicClinic'),
        ),
    ]
