# Generated by Django 3.0.3 on 2020-08-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_remove_packages_packageclinics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='clinicState',
        ),
    ]
