# Generated by Django 3.0.3 on 2020-08-14 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_remove_packages_clinicstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='package_list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='packages',
            name='package_update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
