# Generated by Django 3.0.3 on 2020-10-05 15:20

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0034_basicclinic_fertilitycommunity_email'),
        ('packages', '0010_auto_20200815_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagetitle', models.CharField(blank=True, max_length=30, null=True)),
                ('packagecategory', models.CharField(choices=[('IVF packages', 'IVF packages'), ('Egg Donation', 'Egg Donation'), ('Embryo Donation', 'Embryo Donation')], default='IVF packages', max_length=40, null=True)),
                ('packagedesc', ckeditor.fields.RichTextField(blank=True, max_length=800, null=True)),
                ('packagecost', models.FloatField(blank=True, null=True)),
                ('package_list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('package_update_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('packageclinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic.BasicClinic')),
            ],
        ),
    ]
