# Generated by Django 3.0.3 on 2020-10-05 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0034_basicclinic_fertilitycommunity_email'),
        ('packages', '0011_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='packageclinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.BasicClinic'),
        ),
    ]
