# Generated by Django 3.0.3 on 2020-10-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_auto_20201005_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_limit_days',
            field=models.CharField(choices=[('30 Days', '30 Days'), ('90 Days', '90 Days')], default='30 Days', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
