# Generated by Django 3.0.3 on 2020-10-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_package_package_end_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_package_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
