# Generated by Django 3.0.3 on 2020-10-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_package_is_package_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='is_package_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
