# Generated by Django 3.0.3 on 2020-12-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0017_package_package_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
