# Generated by Django 3.0.3 on 2021-04-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0019_package_package_pic_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='packagecategory',
            field=models.CharField(choices=[('Natural IVF packages', 'Natural IVF packages'), ('Mild (Mini) IVF packages', 'Mild (Mini) IVF packages'), ('Standard IVF packages', 'Standard IVF packages'), ('Egg donation packages', 'Egg donation packages'), ('Embryo donation packages', 'Embryo donation packages')], default='Natural IVF packages', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='packagescategory',
            field=models.CharField(choices=[('Natural IVF packages', 'Natural IVF packages'), ('Mild (Mini) IVF packages', 'Mild (Mini) IVF packages'), ('Standard IVF packages', 'Standard IVF packages'), ('Egg donation packages', 'Egg donation packages'), ('Embryo donation packages', 'Embryo donation packages')], default='Natural IVF packages', max_length=40, null=True),
        ),
    ]
