# Generated by Django 3.0.3 on 2021-11-15 07:29

import clinic.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0020_auto_20210428_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_pic',
            field=models.ImageField(blank=True, null=True, upload_to='ownerPhotos', validators=[clinic.validators.validate_file_size]),
        ),
    ]
