# Generated by Django 3.2.11 on 2022-04-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0021_auto_20211115_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
