# Generated by Django 3.0.3 on 2020-02-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_claimclinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimclinic',
            name='claimUrl',
            field=models.URLField(blank=True, max_length=800),
        ),
    ]
