# Generated by Django 3.0.3 on 2020-02-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200219_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactTitle', models.CharField(max_length=40)),
                ('contactMessage', models.TextField(blank=True, max_length=800)),
            ],
        ),
    ]
