# Generated by Django 3.0.3 on 2020-02-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactwebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactwebsite',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=60),
        ),
    ]
