# Generated by Django 3.0.3 on 2020-12-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pic_blog', models.ImageField(blank=True, null=True, upload_to='blogPhotos')),
                ('tag', models.CharField(choices=[('IVF-Abroad', 'IVF-Abroad')], max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('blog_url', models.URLField()),
                ('minute_read', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=40)),
                ('author_lastname', models.CharField(max_length=40)),
                ('author_pic', models.ImageField(blank=True, null=True, upload_to='authorPhotos')),
                ('author_small_bio', models.CharField(max_length=250)),
                ('author_description', models.TextField()),
                ('linkedin_url', models.URLField()),
                ('facebook_url', models.URLField()),
                ('twitter_url', models.URLField()),
                ('additional_url', models.URLField()),
                ('author_page_url', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
        ),
    ]
