# Generated by Django 3.0.3 on 2021-02-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210213_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.CharField(choices=[('IVF-Abroad', 'IVF-Abroad'), ('IVF Packages', 'IVF Packages'), ('IVF Costs', 'IVF Costs')], max_length=40, null=True),
        ),
    ]
