# Generated by Django 3.0.3 on 2021-04-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210228_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.CharField(choices=[('IVF-Abroad', 'IVF-Abroad'), ('IVF Packages', 'IVF Packages'), ('IVF Costs', 'IVF Costs'), ('Educational', 'Educational')], max_length=40, null=True),
        ),
    ]
