# Generated by Django 3.0.3 on 2021-09-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0075_auto_20210919_1321'),
        ('blog', '0009_bestclinicarticle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BestClinicArticle',
            new_name='BestClinicArticleCountry',
        ),
    ]
