# Generated by Django 3.0.3 on 2021-09-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210919_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestclinicarticlecity',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bestclinicarticlecountry',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bestclinicarticlestate',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
