# Generated by Django 3.0.3 on 2021-10-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210919_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestclinicarticlecity',
            name='best_article_city_noindex_sitemap_boolean',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bestclinicarticlecountry',
            name='best_article_country_noindex_sitemap_boolean',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bestclinicarticlestate',
            name='best_article_state_noindex_sitemap_boolean',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
