# Generated by Django 3.0.3 on 2021-10-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20211004_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestclinicarticlecity',
            name='meta_description',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='bestclinicarticlecountry',
            name='meta_description',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='bestclinicarticlestate',
            name='meta_description',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
