# Generated by Django 3.0.3 on 2021-11-15 07:29

import clinic.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20211031_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_pic',
            field=models.ImageField(blank=True, null=True, upload_to='authorPhotos', validators=[clinic.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='bestclinicarticlecity',
            name='pic_blog',
            field=models.ImageField(blank=True, null=True, upload_to='blogPhotos', validators=[clinic.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='bestclinicarticlecountry',
            name='pic_blog',
            field=models.ImageField(blank=True, null=True, upload_to='blogPhotos', validators=[clinic.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='bestclinicarticlestate',
            name='pic_blog',
            field=models.ImageField(blank=True, null=True, upload_to='blogPhotos', validators=[clinic.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pic_blog',
            field=models.ImageField(blank=True, null=True, upload_to='blogPhotos', validators=[clinic.validators.validate_file_size]),
        ),
    ]
