# Generated by Django 3.0.3 on 2021-12-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20211115_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2022, null=True),
        ),
    ]
