# Generated by Django 3.2.11 on 2022-04-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.CharField(choices=[('IVF-Abroad', 'IVF-Abroad'), ('IVF Packages', 'IVF Packages'), ('IVF Costs', 'IVF Costs'), ('Educational', 'Educational'), ('Informational&Supportive', 'Informational&Supportive'), ('Research', 'Research')], max_length=40, null=True),
        ),
    ]
