# Generated by Django 3.2.11 on 2022-04-26 15:47

import clinic.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_blog_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pic_blog', models.ImageField(blank=True, null=True, upload_to='blogPhotos', validators=[clinic.validators.validate_file_size])),
                ('tag', models.CharField(choices=[('IVF-Abroad', 'IVF-Abroad'), ('IVF Packages', 'IVF Packages'), ('IVF Costs', 'IVF Costs'), ('Educational', 'Educational'), ('Informational&Supportive', 'Informational&Supportive'), ('Research', 'Research')], max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('minute_read', models.IntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, default=2022, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries_faq_article', to='blog.author')),
            ],
        ),
    ]
