# Generated by Django 3.2.11 on 2022-04-26 16:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_faqblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqblog',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='faqblog',
            name='keywords',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='faqblog',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
