# Generated by Django 3.2.11 on 2022-04-26 16:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20220426_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqblog',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
