# Generated by Django 3.2.11 on 2022-05-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20220504_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simpleblog',
            old_name='slug',
            new_name='simple_slug',
        ),
    ]
