# Generated by Django 3.2.11 on 2022-05-17 17:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_rename_slug_simpleblog_simple_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqblog',
            name='tag',
        ),
        migrations.AddField(
            model_name='faqblog',
            name='faq_answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faqblog',
            name='faq_question',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqblog',
            name='faq_simple_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faq_simple_blog_reverse', to='blog.simpleblog'),
        ),
    ]
