# Generated by Django 3.2.11 on 2022-05-23 16:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20220517_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqblog',
            name='faq_old_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faq_blog_reverse', to='blog.blog'),
        ),
        migrations.AddField(
            model_name='faqblog',
            name='faq_old_blog_answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faqblog',
            name='faq_old_blog_question',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
