# Generated by Django 3.2.11 on 2022-05-30 05:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20220523_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqblog',
            name='faq_bestclinicarticlecity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faq_bestclinicarticlecity_reverse', to='blog.bestclinicarticlecity'),
        ),
        migrations.AddField(
            model_name='faqblog',
            name='faq_bestclinicarticlecity_answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faqblog',
            name='faq_bestclinicarticlecity_question',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='faqblog',
            name='faq_old_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faq_old_blog_reverse', to='blog.blog'),
        ),
    ]
