# Generated by Django 3.2.11 on 2022-06-05 08:48

import ckeditor.fields
import clinic.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20220530_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqblog',
            name='faq_best_clinic_article_state_answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faqblog',
            name='faq_best_clinic_article_state_question',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ModularBestClinics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=150)),
                ('keywords', models.CharField(blank=True, max_length=150, null=True)),
                ('pic_blog', models.ImageField(blank=True, null=True, upload_to='blogPhotos', validators=[clinic.validators.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('minute_read', models.IntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, default=2022, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_modular_article', to='blog.author')),
            ],
        ),
        migrations.AddField(
            model_name='faqblog',
            name='faq_best_clinic_article_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faq_modular_best_clinics_reverse', to='blog.modularbestclinics'),
        ),
    ]
