# Generated by Django 3.2.11 on 2022-06-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20220605_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modularbestclinics',
            old_name='slug',
            new_name='modular_slug',
        ),
    ]
