# Generated by Django 3.2.11 on 2022-06-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20220605_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='modularbestclinics',
            name='link_fertility_clinics',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
