# Generated by Django 3.2.11 on 2022-06-27 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20220606_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modularbestclinics',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
