# Generated by Django 3.0.3 on 2020-02-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20200210_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicclinic',
            name='clinicName',
            field=models.CharField(max_length=35),
        ),
    ]
