# Generated by Django 3.0.3 on 2020-02-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_auto_20200212_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='fridayCloses',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='fridayOpens',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='mondayCloses',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='mondayOpens',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='saturdayCloses',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='saturdayOpens',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='sundayCloses',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='sundayOpens',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='thursdayCloses',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='thursdayOpens',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='tuesdayCloses',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='tuesdayOpens',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='wednesdayCloses',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='wednesdayOpens',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
