# Generated by Django 3.0.3 on 2020-02-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20200219_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='clinicOwn',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Private', 'Private'), ('State', 'State')], max_length=40, null=True),
        ),
    ]
