# Generated by Django 3.0.3 on 2020-02-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_basicclinic_clinicenglishlanguage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicclinic',
            name='clinicEnglishLanguage',
        ),
    ]
