# Generated by Django 3.0.3 on 2020-03-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_auto_20200229_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
