# Generated by Django 3.0.3 on 2020-03-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_basicclinic_is_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='clinicChinese',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='defaultClinicCurrency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], max_length=40, null=True),
        ),
    ]
