# Generated by Django 3.0.3 on 2020-03-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_basicclinic_treatmentlimitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='sex_selection',
            field=models.BooleanField(default=False),
        ),
    ]
