# Generated by Django 3.0.3 on 2020-03-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_basicclinic_sex_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='no_waiting_list',
            field=models.BooleanField(default=False),
        ),
    ]
