# Generated by Django 3.0.3 on 2020-03-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_auto_20200310_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='type',
            field=models.CharField(choices=[('Clinic', 'Clinic'), ('Agency', 'Agency')], default='Clinic', max_length=40, null=True),
        ),
    ]
