# Generated by Django 3.0.3 on 2020-03-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_auto_20200311_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='mild_ivf_treatment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='mild_ivf_treatment_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='ovarian_ivf_treatment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='ovarian_ivf_treatment_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
