# Generated by Django 3.0.3 on 2020-03-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_auto_20200322_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='package1cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package1desc',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package1title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
