# Generated by Django 3.0.3 on 2020-03-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_auto_20200325_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='package2cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package2desc',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package2title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package3cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package3desc',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package3title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package4cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package4desc',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package4title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package5cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package5desc',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package5title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package6cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package6desc',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package6title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='team1name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='team1pic',
            field=models.ImageField(blank=True, null=True, upload_to='ownerPhotos'),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='team2name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='team2pic',
            field=models.ImageField(blank=True, null=True, upload_to='ownerPhotos'),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='team3name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='team3pic',
            field=models.ImageField(blank=True, null=True, upload_to='ownerPhotos'),
        ),
    ]
