# Generated by Django 3.0.3 on 2020-03-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_auto_20200325_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicclinic',
            name='package1desc',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='package2desc',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='package3desc',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='package4desc',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='package5desc',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='package6desc',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
