# Generated by Django 3.0.3 on 2020-05-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0024_basicclinic_query_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='package1category',
            field=models.CharField(choices=[('IVF', 'IVF'), ('Egg Donation', 'Egg Donation'), ('Embryo Donation', 'Embryo Donation')], default='IVF', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package2category',
            field=models.CharField(choices=[('IVF', 'IVF'), ('Egg Donation', 'Egg Donation'), ('Embryo Donation', 'Embryo Donation')], default='IVF', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package3category',
            field=models.CharField(choices=[('IVF', 'IVF'), ('Egg Donation', 'Egg Donation'), ('Embryo Donation', 'Embryo Donation')], default='IVF', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package4category',
            field=models.CharField(choices=[('IVF', 'IVF'), ('Egg Donation', 'Egg Donation'), ('Embryo Donation', 'Embryo Donation')], default='IVF', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package5category',
            field=models.CharField(choices=[('IVF', 'IVF'), ('Egg Donation', 'Egg Donation'), ('Embryo Donation', 'Embryo Donation')], default='IVF', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='package6category',
            field=models.CharField(choices=[('IVF', 'IVF'), ('Egg Donation', 'Egg Donation'), ('Embryo Donation', 'Embryo Donation')], default='IVF', max_length=40, null=True),
        ),
    ]
