# Generated by Django 3.0.3 on 2020-05-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0025_auto_20200516_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicclinic',
            name='package1title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='package2title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='package3title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='package4title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='package5title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='package6title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
