# Generated by Django 3.0.3 on 2020-05-16 18:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0026_auto_20200516_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicclinic',
            name='clinic_staff',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='package1desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='package2desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='package3desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='package4desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='package5desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='package6desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
