# Generated by Django 3.0.3 on 2020-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0027_auto_20200516_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='clinicCityLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='clinicLocationLink',
            field=models.URLField(blank=True, default='https://www.fertilitycommunity.com/locations', null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='clinicRegionLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='clinicStateLink',
            field=models.URLField(blank=True, default='https://www.fertilitycommunity.com/locations/us-regions', null=True),
        ),
    ]
