# Generated by Django 3.0.3 on 2020-07-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0028_auto_20200518_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicclinic',
            name='clinicStateLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
