# Generated by Django 3.0.3 on 2020-07-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0029_auto_20200715_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicclinic',
            name='clinicLocationLink',
            field=models.URLField(blank=True, default='https://www.fertilitycommunity.com/ivf-cost', null=True),
        ),
    ]
