# Generated by Django 3.0.3 on 2020-07-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0030_auto_20200715_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='follow_up_consultation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='follow_up_consultation_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='initial_consultation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='initial_consultation_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='known_egg_donor_recipients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='known_egg_donor_recipients_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='known_embryo_donor_recipients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='known_embryo_donor_recipients_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='known_sperm_donor_recipients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='known_sperm_donor_recipients_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='pgta_pgs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='pgta_pgs_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='pgtst_pgs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='pgtst_pgs_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='shared_egg_donor_recipients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='shared_egg_donor_recipients_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
