# Generated by Django 3.0.3 on 2020-07-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0031_auto_20200728_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='egg_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='egg_donor_compensation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='egg_donor_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='egg_sharing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='egg_sharing_compensation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='egg_sharing_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='sperm_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='sperm_donor_compensation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='sperm_donor_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='type',
            field=models.CharField(choices=[('Clinic', 'Clinic'), ('Agency', 'Agency'), ('DonorBank', 'DonorBank')], default='Clinic', max_length=40, null=True),
        ),
    ]
