# Generated by Django 3.0.3 on 2020-09-19 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0032_auto_20200728_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayProCustomerClinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeid', models.CharField(max_length=255)),
                ('stripe_subscription_id', models.CharField(max_length=255)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('membership', models.BooleanField(default=False)),
                ('proClinic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proClinic', to='clinic.BasicClinic')),
            ],
        ),
    ]
