# Generated by Django 3.0.3 on 2020-10-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0033_payprocustomerclinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='fertilitycommunity_email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
