# Generated by Django 3.0.3 on 2020-10-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0034_basicclinic_fertilitycommunity_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='packageClinicCounterNumber',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
