# Generated by Django 3.0.3 on 2020-10-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0036_auto_20201005_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicsExportProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.basicclinic',),
        ),
    ]
