# Generated by Django 3.0.3 on 2020-11-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0037_clinicsexportproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='is_not_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='defaultClinicCurrency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR')], max_length=40, null=True),
        ),
    ]
