# Generated by Django 3.0.3 on 2020-12-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0039_auto_20201201_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='clinic_pro_logo_pic_del',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='clinic_pro_photo_1_del',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='clinic_pro_photo_2_del',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='clinic_pro_photo_3_del',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='clinic_pro_photo_4_del',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='clinic_pro_photo_5_del',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='clinic_pro_photo_6_del',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='team1pic_del',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='team2pic_del',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='team3pic_del',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
