# Generated by Django 3.0.3 on 2021-03-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0040_auto_20201218_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='guestAuthorCounterNumber',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='guestBlogCounterNumber',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
