# Generated by Django 3.0.3 on 2021-04-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0041_auto_20210302_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='clinicChatraCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='defaultClinicCurrency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR'), ('MXN', 'MXN')], max_length=40, null=True),
        ),
    ]
