# Generated by Django 3.0.3 on 2021-04-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0042_auto_20210420_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='clinicLiveChatChoice',
            field=models.CharField(choices=[('Chatra.com', 'Chatra.com'), ('Livechat.com', 'Livechat.com')], max_length=40, null=True),
        ),
    ]
