# Generated by Django 3.0.3 on 2021-04-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0043_basicclinic_cliniclivechatchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='clinicLiveChatCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
