# Generated by Django 3.0.3 on 2021-04-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0044_basicclinic_cliniclivechatcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicclinic',
            name='clinicLiveChatChoice',
            field=models.CharField(blank=True, choices=[('Chatra.com', 'Chatra.com'), ('Livechat.com', 'Livechat.com')], max_length=40, null=True),
        ),
    ]
