# Generated by Django 3.0.3 on 2021-04-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0045_auto_20210420_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='clinicOlarkCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='clinicTidioCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='clinicLiveChatChoice',
            field=models.CharField(blank=True, choices=[('Chatra', 'Chatra'), ('Livechat', 'Livechat'), ('Livechat', 'Livechat'), ('Tidio', 'Tidio')], max_length=40, null=True),
        ),
    ]
