# Generated by Django 3.0.3 on 2021-04-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0047_auto_20210420_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='clinicGoogleReviews',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='clinicTrustPilotID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
