# Generated by Django 3.0.3 on 2021-04-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0050_basicclinic_clinictrustpilotdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='clinicTrustPilotChoice',
            field=models.CharField(blank=True, choices=[('Micro Review Count', 'Micro Review Count'), ('Mini', 'Mini')], max_length=40, null=True),
        ),
    ]
