# Generated by Django 3.0.3 on 2021-04-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0051_basicclinic_clinictrustpilotchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='accepts_patients_from_abroad',
            field=models.BooleanField(default=False),
        ),
    ]
