# Generated by Django 3.0.3 on 2021-05-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0052_basicclinic_accepts_patients_from_abroad'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='clinicFacebook',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='clinicInstagram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='clinicLinkedIn',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='clinicPinterest',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='clinicTwitter',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='clinicYoutube',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
