# Generated by Django 3.0.3 on 2021-06-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0056_basicclinic_digitaltransparencyindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicclinic',
            name='digitalTransparencyIndex',
            field=models.PositiveSmallIntegerField(blank=True, default=100, null=True),
        ),
    ]
