# Generated by Django 3.0.3 on 2021-06-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0057_auto_20210604_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicclinic',
            name='digitalTransparencyIndex',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
