# Generated by Django 3.0.3 on 2021-08-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0058_auto_20210604_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='assisted_hatching_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='egg_donor_recipients_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='egg_freezing_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='embryo_donor_recipients_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='embryo_freezing_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='fertility_preservation_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='follow_up_consultation_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='icsi_treatment_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='initial_consultation_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='iui_treatment_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='ivf_treatment_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='known_egg_donor_recipients_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='known_embryo_donor_recipients_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='known_sperm_donor_recipients_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='mild_ivf_treatment_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='ovarian_ivf_treatment_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='pgd_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='pgta_pgs_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='pgtst_pgs_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='shared_egg_donor_recipients_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='sperm_donor_recipients_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='sperm_freezing_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='surrogacy_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='vasectomy_reversal_faqs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
