# Generated by Django 3.0.3 on 2021-08-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0059_auto_20210801_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='team1position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='team2position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='team3position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
