# Generated by Django 3.0.3 on 2021-09-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0061_auto_20210904_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='accepted_currency_type',
            field=models.ManyToManyField(to='clinic.AcceptedCurrency'),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='accepted_payment_type',
            field=models.ManyToManyField(to='clinic.AcceptedPayment'),
        ),
    ]
