# Generated by Django 3.0.3 on 2021-09-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0063_auto_20210904_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedcurrency',
            name='accepted_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='acceptedpayment',
            name='accepted_payment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
