# Generated by Django 3.0.3 on 2021-09-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0065_auto_20210904_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='payment_type_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='payment_type_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='payment_type_cryptocurrency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='payment_type_debit_cards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='payment_type_major_credit_cards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='payment_type_wire_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='accepted_payment_type',
            field=models.ManyToManyField(blank=True, related_name='payment_types_related_name', to='clinic.AcceptedPayment'),
        ),
    ]
