# Generated by Django 3.0.3 on 2021-09-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0066_auto_20210905_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicclinic',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
