# Generated by Django 3.0.3 on 2021-09-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0068_auto_20210905_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicclinic',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
