# Generated by Django 3.0.3 on 2021-09-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0071_auto_20210914_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='best_article_country_actual_prototype',
            field=models.TextField(blank=True, max_length=1300, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='best_article_country_actual_text',
            field=models.TextField(blank=True, max_length=1300, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='best_article_country_boolean',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
