# Generated by Django 3.0.3 on 2021-09-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0072_auto_20210918_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicclinic',
            name='best_article_country_actual_prototype',
            field=models.TextField(blank=True, max_length=3600, null=True),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='best_article_country_actual_text',
            field=models.TextField(blank=True, max_length=3600, null=True),
        ),
    ]
