# Generated by Django 3.0.3 on 2021-09-19 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210731_0803'),
        ('clinic', '0073_auto_20210918_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='best_article_country_blogpost_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='best_article_country_fk', to='blog.Blog'),
        ),
    ]
