# Generated by Django 3.0.3 on 2021-09-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210919_1341'),
        ('clinic', '0075_auto_20210919_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='best_article_city_actual_prototype',
            field=models.TextField(blank=True, max_length=3600, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='best_article_city_actual_text',
            field=models.TextField(blank=True, max_length=3600, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='best_article_city_blogpost_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='best_article_city_fk', to='blog.BestClinicArticleCity'),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='best_article_city_boolean',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='best_article_state_actual_prototype',
            field=models.TextField(blank=True, max_length=3600, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='best_article_state_actual_text',
            field=models.TextField(blank=True, max_length=3600, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='best_article_state_blogpost_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='best_article_state_fk', to='blog.BestClinicArticleState'),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='best_article_state_boolean',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
