# Generated by Django 3.0.3 on 2021-11-15 07:29

import clinic.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0080_auto_20211004_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicclinic',
            name='clinic_pro_logo_pic',
            field=models.ImageField(blank=True, null=True, upload_to='ownerPhotos', validators=[clinic.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='clinic_pro_main_pic',
            field=models.ImageField(blank=True, null=True, upload_to='ownerPhotos', validators=[clinic.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='clinic_pro_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='ownerPhotos', validators=[clinic.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='clinic_pro_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='ownerPhotos', validators=[clinic.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='clinic_pro_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='ownerPhotos', validators=[clinic.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='clinic_pro_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='ownerPhotos', validators=[clinic.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='clinic_pro_photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='ownerPhotos', validators=[clinic.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='clinic_pro_photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='ownerPhotos', validators=[clinic.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='team1pic',
            field=models.ImageField(blank=True, null=True, upload_to='ownerPhotos', validators=[clinic.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='team2pic',
            field=models.ImageField(blank=True, null=True, upload_to='ownerPhotos', validators=[clinic.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='team3pic',
            field=models.ImageField(blank=True, null=True, upload_to='ownerPhotos', validators=[clinic.validators.validate_file_size]),
        ),
    ]
