# Generated by Django 3.0.3 on 2022-01-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0081_auto_20211115_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='active_180',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='active_30',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='active_90',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
