# Generated by Django 3.2.11 on 2022-01-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0082_auto_20220106_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicclinic',
            name='defaultClinicCurrency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD')], default='USD', max_length=40, null=True),
        ),
    ]
