# Generated by Django 3.2.11 on 2022-05-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0085_alter_basicclinic_experts'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='best_article_city_accommodation_section_content',
            field=models.TextField(blank=True, max_length=3750, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='best_article_city_distance_section_content',
            field=models.TextField(blank=True, max_length=3750, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='best_article_city_google_reviews_section_content',
            field=models.TextField(blank=True, max_length=3750, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='best_article_city_packages_section_content',
            field=models.TextField(blank=True, max_length=3750, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='best_article_city_pricing_section_content',
            field=models.TextField(blank=True, max_length=3750, null=True),
        ),
    ]
