# Generated by Django 3.2.11 on 2022-05-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0086_auto_20220504_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicclinic',
            options={'ordering': ['id']},
        ),
    ]
