# Generated by Django 3.2.11 on 2022-06-05 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20220605_0957'),
        ('clinic', '0087_alter_basicclinic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='modular_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='best_modular_city', to='blog.modularbestclinics'),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='modular_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='best_modular_country', to='blog.modularbestclinics'),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='modular_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='best_modular_state', to='blog.modularbestclinics'),
        ),
    ]
