# Generated by Django 3.2.11 on 2022-06-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0088_auto_20220605_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='modular_city_actual_prototype',
            field=models.TextField(blank=True, max_length=3750, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='modular_city_actual_text',
            field=models.TextField(blank=True, max_length=3750, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='modular_city_fcreview_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='modular_country_actual_prototype',
            field=models.TextField(blank=True, max_length=3750, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='modular_country_actual_text',
            field=models.TextField(blank=True, max_length=3750, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='modular_country_fcreview_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='modular_state_actual_prototype',
            field=models.TextField(blank=True, max_length=3750, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='modular_state_actual_text',
            field=models.TextField(blank=True, max_length=3750, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='modular_state_fcreview_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
