# Generated by Django 3.2.11 on 2022-06-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0089_auto_20220605_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='modular_city_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='modular_country_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='modular_state_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
