# Generated by Django 3.2.11 on 2022-08-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0090_auto_20220605_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclinic',
            name='choices_of_best_list',
            field=models.CharField(blank=True, choices=[('1', 'Value for money'), ('2', 'Renowned surgeons'), ('3', 'Professional staff'), ('4', 'Honest expectations'), ('1', 'Brilliant attention from staff'), ('2', 'Excellent customer care'), ('3', 'Friendly staff'), ('4', 'Stress-free treatment'), ('1', 'Outstanding aftercare')], max_length=500, null=True),
        ),
    ]
