# Generated by Django 3.2.11 on 2022-08-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0091_basicclinic_choices_of_best_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicclinic',
            name='choices_of_best_list',
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='choices_of_best_list_city',
            field=models.CharField(blank=True, choices=[('Value for money', 'Value for money'), ('Renowned surgeons', 'Renowned surgeons'), ('Professional staff', 'Professional staff'), ('Honest expectations', 'Honest expectations'), ('Brilliant attention from staff', 'Brilliant attention from staff'), ('Excellent customer care', 'Excellent customer care'), ('Friendly staff', 'Friendly staff'), ('Stress-free treatment', 'Stress-free treatment'), ('Outstanding aftercare', 'Outstanding aftercare')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='choices_of_best_list_country',
            field=models.CharField(blank=True, choices=[('Value for money', 'Value for money'), ('Renowned surgeons', 'Renowned surgeons'), ('Professional staff', 'Professional staff'), ('Honest expectations', 'Honest expectations'), ('Brilliant attention from staff', 'Brilliant attention from staff'), ('Excellent customer care', 'Excellent customer care'), ('Friendly staff', 'Friendly staff'), ('Stress-free treatment', 'Stress-free treatment'), ('Outstanding aftercare', 'Outstanding aftercare')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicclinic',
            name='choices_of_best_list_state',
            field=models.CharField(blank=True, choices=[('Value for money', 'Value for money'), ('Renowned surgeons', 'Renowned surgeons'), ('Professional staff', 'Professional staff'), ('Honest expectations', 'Honest expectations'), ('Brilliant attention from staff', 'Brilliant attention from staff'), ('Excellent customer care', 'Excellent customer care'), ('Friendly staff', 'Friendly staff'), ('Stress-free treatment', 'Stress-free treatment'), ('Outstanding aftercare', 'Outstanding aftercare')], max_length=500, null=True),
        ),
    ]
