# Generated by Django 3.2.11 on 2022-08-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_alter_modularbestclinics_description'),
        ('clinic', '0092_auto_20220821_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicclinic',
            name='modular_city',
            field=models.ForeignKey(blank=True, limit_choices_to={'country': None, 'state': None}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='best_modular_city', to='blog.modularbestclinics'),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='modular_country',
            field=models.ForeignKey(blank=True, limit_choices_to={'city': None, 'state': None}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='best_modular_country', to='blog.modularbestclinics'),
        ),
        migrations.AlterField(
            model_name='basicclinic',
            name='modular_state',
            field=models.ForeignKey(blank=True, limit_choices_to={'city': None, 'country': None}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='best_modular_state', to='blog.modularbestclinics'),
        ),
    ]
