from django.contrib import sitemaps
from django.urls import reverse
from base import views
from searchLocationsRegionsUS import views
from location import views
from clinicsUS import views

class ClinicsViewSitemap(sitemaps.Sitemap):
    changefreq = "daily"
    priority = 0.5
    protocol = "https"

    def items(self):
        return [
        'wfi',
        'cifc',
        'ncfmcr',
        'ncfmcs',
        'liwla',
        'lip',
        'lich',
        'tcfrm',
        'af',
        'tfc',
        'tfg',
        'tfm',
        'sfc',
        'afcs',
        'afcm',
        'aafrhs',
        'aafrhg',
        'bris',
        'brig',
        'biacs',
        'biacch',
        'biacp',
        'biacf',
        'ip',
        'ftc',
        'arifc',
        'irmsco',
        'irmsewo',
        'irmsho',
        'irmshbo',
        'irmsnjo',
        'irmslo',
        'irmsobo',
        'cfnyc',
        'ccrmnyfc',
        'afg',
        'ccrmcmclt',
        'ccrmcdo',
        'ccrmclo',
        'ucarmd',
        'ucarmcos',
        'rmcrm',
        'carsf',
        'carsh',
        'carsnl',
        'carsb',
        'gfg',
        'gfs',
        'rmactn',
        'rmacts',
        'rmactd',
        'rmactt',
        'paft',
        'dirmn',
        'dirmm',
        'radfn',
        'radfw',
        'radfd',
        'bocaf',
        'pbfcbr',
        'pbfcpbg',
        'ffico',
        'ffito',
        'cfcg',
        'cfm',
        'jcrmj',
        'jcrmg',
        'jcrmpc',
        'jcrmo',
        'rmanlm',
        'ivffwfc',
        'ivffcgfc',
        'ivfppfc',
        'ivffmfc',
        'ivfbrfc',
        'ivffjpbgfc',
        'ivffplfc',
        'vfc',
        'fivfcm',
        'fivfcmb',
        'fg',
        'ivfmdm',
        'ivfmdcc',
        'ivfmdbr',
        'ivfmdj',
        'ivfmdn',
        'ivfmdv',
        'sgftw',
        'sgfb',
        'sgfwc',
        'rmgnto',
        'rmgsto',
        'rmgco',
        'rmgbo',
        'fifrst',
        'arswp',
        'ivfowp',
        'fcare',
        ]

    def location(self, item):
        return reverse(item)
