# Generated by Django 3.2.11 on 2022-02-13 16:54

import clinic.validators
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_profile_photo', models.ImageField(upload_to='fertility_coach', validators=[clinic.validators.validate_file_size])),
                ('coach_profile_photo_delete', models.BooleanField(blank=True, default=False, null=True)),
                ('coach_full_name', models.CharField(max_length=100)),
                ('coach_username', models.SlugField(help_text='Use as slug in URL', max_length=25)),
                ('coach_bio', models.TextField(blank=True, null=True)),
                ('coach_contact_email', models.EmailField(blank=True, max_length=256, null=True)),
                ('coach_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('coach_social_instagram', models.URLField(blank=True, null=True)),
                ('coach_social_facebook', models.URLField(blank=True, null=True)),
                ('coach_social_linkedin', models.URLField(blank=True, null=True)),
                ('coach_social_pinterest', models.URLField(blank=True, null=True)),
                ('coach_social_twitter', models.URLField(blank=True, null=True)),
                ('coach_social_website', models.URLField(blank=True, null=True)),
                ('coach_prefered_client_country', models.CharField(blank=True, max_length=256, null=True)),
                ('coach_prefered_client_city', models.CharField(blank=True, max_length=256, null=True)),
                ('coach_prefered_languages', models.CharField(blank=True, max_length=256, null=True)),
                ('coach_education', models.TextField(blank=True, null=True)),
                ('coach_specialization', models.TextField(blank=True, null=True)),
                ('coach_certification', models.TextField(blank=True, null=True)),
                ('coach_other', models.TextField(blank=True, null=True)),
                ('coach_is_published', models.BooleanField(default=False)),
                ('coach_is_not_approved', models.BooleanField(default=False)),
                ('coach_is_premium', models.BooleanField(default=False)),
                ('coach_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('coach_subscription_update', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('coach_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
