# Generated by Django 3.2.11 on 2022-02-17 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_auto_20220217_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaches',
            name='coach_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
