# Generated by Django 3.2.11 on 2022-02-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0005_coachcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachcategory',
            name='type_1',
        ),
        migrations.RemoveField(
            model_name='coachcategory',
            name='type_2',
        ),
        migrations.RemoveField(
            model_name='coachcategory',
            name='type_3',
        ),
        migrations.RemoveField(
            model_name='coachcategory',
            name='type_4',
        ),
        migrations.RemoveField(
            model_name='coachcategory',
            name='type_5',
        ),
        migrations.RemoveField(
            model_name='coachcategory',
            name='type_6',
        ),
        migrations.RemoveField(
            model_name='coachcategory',
            name='type_7',
        ),
        migrations.RemoveField(
            model_name='coachcategory',
            name='type_8',
        ),
        migrations.AddField(
            model_name='coachcategory',
            name='andrologist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachcategory',
            name='fertility_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachcategory',
            name='fertility_specialist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachcategory',
            name='gynecologist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachcategory',
            name='obstetrician',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachcategory',
            name='reproductive_endocrinologist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachcategory',
            name='reproductive_immunologist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachcategory',
            name='reproductive_surgeon',
            field=models.BooleanField(default=False),
        ),
    ]
