# Generated by Django 3.2.11 on 2022-02-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0006_auto_20220217_1920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoachCategory',
        ),
    ]
