# Generated by Django 3.2.11 on 2022-02-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0007_delete_coachcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_job', models.CharField(blank=True, max_length=256, null=True)),
                ('coaches_relationship', models.ManyToManyField(related_name='jobs', to='coaches.Coaches')),
            ],
        ),
    ]
