# Generated by Django 3.2.11 on 2022-02-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0008_typejobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typejobs',
            name='coaches_relationship',
            field=models.ManyToManyField(blank=True, null=True, related_name='jobs', to='coaches.Coaches'),
        ),
    ]
