# Generated by Django 3.2.11 on 2022-02-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0012_preferredcountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('snippet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaches.coaches')),
            ],
        ),
    ]
