# Generated by Django 3.2.11 on 2022-02-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0017_snippetnew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
