# Generated by Django 3.2.11 on 2022-02-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0018_delete_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippetnew',
            name='is_not_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snippetnew',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
