# Generated by Django 3.2.11 on 2022-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0019_auto_20220219_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippetnew',
            name='is_not_approved',
        ),
        migrations.RemoveField(
            model_name='snippetnew',
            name='is_published',
        ),
        migrations.AddField(
            model_name='snippetnew',
            name='status',
            field=models.CharField(choices=[('wait for review', 'wait for review'), ('is published', 'is published'), ('is not approved', 'is not approved')], default='wait for review', max_length=40, null=True),
        ),
    ]
