# Generated by Django 3.2.11 on 2022-02-19 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0020_auto_20220219_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetnew',
            name='snippet_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_jobs', to='coaches.coaches'),
        ),
    ]
