# Generated by Django 3.2.11 on 2022-02-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0024_alter_snippetnew_snippet_blog_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaches',
            name='job_andrologist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coaches',
            name='job_fertility_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coaches',
            name='job_fertility_specialist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coaches',
            name='job_gynecologist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coaches',
            name='job_obstetrician',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coaches',
            name='job_reproductive_immunologist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coaches',
            name='job_reproductive_ndocrinologist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coaches',
            name='job_reproductive_surgeon',
            field=models.BooleanField(default=False),
        ),
    ]
