# Generated by Django 3.2.11 on 2022-02-20 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0025_auto_20220220_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coaches',
            old_name='job_reproductive_ndocrinologist',
            new_name='job_reproductive_endocrinologist',
        ),
    ]
