# Generated by Django 3.2.11 on 2022-02-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog_year'),
        ('coaches', '0026_rename_job_reproductive_ndocrinologist_coaches_job_reproductive_endocrinologist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetnew',
            name='snippet_blog_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_blog_conn', to='blog.blog'),
        ),
    ]
