# Generated by Django 3.2.11 on 2022-02-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog_year'),
        ('coaches', '0027_alter_snippetnew_snippet_blog_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippetnew',
            name='snippet_m2m',
            field=models.ManyToManyField(blank=True, related_name='snippet_m2m', to='blog.Blog'),
        ),
    ]
