# Generated by Django 3.2.11 on 2022-02-23 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0028_snippetnew_snippet_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippetnew',
            name='snippet_m2m',
        ),
    ]
