# Generated by Django 3.2.11 on 2022-02-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0029_remove_snippetnew_snippet_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaches',
            name='coach_preferred_languages',
            field=models.TextField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('Chinese', 'Chinese'), ('Portuguese', 'Portuguese'), ('Spanish', 'Spanish')], max_length=256, null=True),
        ),
    ]
