# Generated by Django 3.2.11 on 2022-03-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog_year'),
        ('coaches', '0031_alter_coaches_coach_preferred_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('wait for review', 'wait for review'), ('is published', 'is published'), ('is not approved', 'is not approved')], default='wait for review', max_length=40, null=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_blog', to='blog.blog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippet_owner', to='coaches.coaches')),
            ],
        ),
    ]
