# Generated by Django 3.2.11 on 2022-03-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0032_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coaches',
            name='job_andrologist',
        ),
        migrations.RemoveField(
            model_name='coaches',
            name='job_fertility_coach',
        ),
        migrations.RemoveField(
            model_name='coaches',
            name='job_fertility_specialist',
        ),
        migrations.RemoveField(
            model_name='coaches',
            name='job_gynecologist',
        ),
        migrations.RemoveField(
            model_name='coaches',
            name='job_obstetrician',
        ),
        migrations.RemoveField(
            model_name='coaches',
            name='job_reproductive_endocrinologist',
        ),
        migrations.RemoveField(
            model_name='coaches',
            name='job_reproductive_immunologist',
        ),
        migrations.RemoveField(
            model_name='coaches',
            name='job_reproductive_surgeon',
        ),
    ]
