# Generated by Django 3.2.11 on 2022-03-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0036_alter_coaches_coach_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaches',
            name='coach_social_youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
