# Generated by Django 3.2.11 on 2022-04-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog_year'),
        ('coaches', '0037_coaches_coach_social_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coaches',
            name='coach_category',
        ),
        migrations.RemoveField(
            model_name='coaches',
            name='coach_preferred_languages',
        ),
        migrations.AddField(
            model_name='coaches',
            name='blog_best_city_review',
            field=models.ManyToManyField(blank=True, related_name='city_reviewed_by', to='blog.BestClinicArticleCity'),
        ),
        migrations.AddField(
            model_name='coaches',
            name='blog_best_country_review',
            field=models.ManyToManyField(blank=True, related_name='country_reviewed_by', to='blog.BestClinicArticleCountry'),
        ),
        migrations.AddField(
            model_name='coaches',
            name='blog_best_state_review',
            field=models.ManyToManyField(blank=True, related_name='state_reviewed_by', to='blog.BestClinicArticleState'),
        ),
        migrations.AddField(
            model_name='coaches',
            name='blog_review',
            field=models.ManyToManyField(blank=True, related_name='blog_reviewed_by', to='blog.Blog'),
        ),
    ]
