# Generated by Django 3.2.11 on 2022-04-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_faqblog_active'),
        ('coaches', '0038_auto_20220403_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaches',
            name='blog_faq_review',
            field=models.ManyToManyField(blank=True, related_name='blog_faq_reviewed_by', to='blog.FAQBlog'),
        ),
    ]
