# Generated by Django 3.2.11 on 2022-05-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0040_snippetsimpleblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaches',
            name='coach_is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
