# Generated by Django 3.0.3 on 2021-05-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenciesexchangerates',
            name='usd_to_cad_exchange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currenciesexchangerates',
            name='usd_to_eur_exchange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currenciesexchangerates',
            name='usd_to_gbp_exchange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currenciesexchangerates',
            name='usd_to_inr_exchange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currenciesexchangerates',
            name='usd_to_mxn_exchange',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
