# Generated by Django 3.2.11 on 2022-01-14 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookiesConsents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Session ID cookie')),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True, verbose_name='IP Adresa')),
                ('analytical_cookies', models.BooleanField(default=False)),
                ('marketing_cookies', models.BooleanField(default=False)),
                ('consent_created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CookieSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytical_cookies_header', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Cookies využívané pro analytiku webu')),
                ('analytical_cookies_footer', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Cookies využívané pro analytiku webu (vložte kód určený do footeru)')),
                ('marketing_cookies_header', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Cookies využívané k reklamním účelům')),
                ('marketing_cookies_footer', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Cookies využívané k reklamním účelům (vložte kód určený do footeru)')),
            ],
        ),
    ]
