# Generated by Django 3.2.11 on 2022-03-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiesconsents',
            name='custom_cookie',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Custom cookie value'),
        ),
    ]
