from django.urls import path

from . import views

urlpatterns = [
    path('locations/us-regions/fertility-clinics-alabama', views.fertilityClinicsAlabama, name='fertilityClinicsAlabama'),
    path('locations/us-regions/fertility-clinics-alaska', views.fertilityClinicsAlaska, name='fertilityClinicsAlaska'),
    path('locations/us-regions/fertility-clinics-arkansas', views.fertilityClinicsArkansas, name='fertilityClinicsArkansas'),
    path('locations/us-regions/fertility-clinics-california', views.fertilityClinicsCalifornia, name='fertilityClinicsCalifornia'),
    path('locations/us-regions/fertility-clinics-colorado', views.fertilityClinicsColorado, name='fertilityClinicsColorado'),
    path('locations/us-regions/fertility-clinics-connecticut', views.fertilityClinicsConnecticut, name='fertilityClinicsConnecticut'),
    path('locations/us-regions/fertility-clinics-delaware', views.fertilityClinicsDelaware, name='fertilityClinicsDelaware'),
    path('locations/us-regions/fertility-clinics-georgia', views.fertilityClinicsGeorgia, name='fertilityClinicsGeorgia'),
    path('locations/us-regions/fertility-clinics-hawaii', views.fertilityClinicsHawaii, name='fertilityClinicsHawaii'),
    path('locations/us-regions/fertility-clinics-idaho', views.fertilityClinicsIdaho, name='fertilityClinicsIdaho'),
    path('locations/us-regions/fertility-clinics-illinois', views.fertilityClinicsIllinois, name='fertilityClinicsIllinois'),
    path('locations/us-regions/fertility-clinics-indiana', views.fertilityClinicsIndiana, name='fertilityClinicsIndiana'),
    path('locations/us-regions/fertility-clinics-iowa', views.fertilityClinicsIowa, name='fertilityClinicsIowa'),
    path('locations/us-regions/fertility-clinics-kansas', views.fertilityClinicsKansas, name='fertilityClinicsKansas'),
    path('locations/us-regions/fertility-clinics-kentucky', views.fertilityClinicsKentucky, name='fertilityClinicsKentucky'),
    path('locations/us-regions/fertility-clinics-louisiana', views.fertilityClinicsLouisiana, name='fertilityClinicsLouisiana'),
    path('locations/us-regions/fertility-clinics-maine', views.fertilityClinicsMaine, name='fertilityClinicsMaine'),
    path('locations/us-regions/fertility-clinics-maryland', views.fertilityClinicsMaryland, name='fertilityClinicsMaryland'),
    path('locations/us-regions/fertility-clinics-massachusetts', views.fertilityClinicsMassachusetts, name='fertilityClinicsMassachusetts'),
    path('locations/us-regions/fertility-clinics-michigan', views.fertilityClinicsMichigan, name='fertilityClinicsMichigan'),
    path('locations/us-regions/fertility-clinics-minnesota', views.fertilityClinicsMinnesota, name='fertilityClinicsMinnesota'),
    path('locations/us-regions/fertility-clinics-mississippi', views.fertilityClinicsMississippi, name='fertilityClinicsMississippi'),
    path('locations/us-regions/fertility-clinics-missouri', views.fertilityClinicsMissouri, name='fertilityClinicsMissouri'),
    path('locations/us-regions/fertility-clinics-nebraska', views.fertilityClinicsNebraska, name='fertilityClinicsNebraska'),
    path('locations/us-regions/fertility-clinics-new-hampshire', views.fertilityClinicsNewHampshire, name='fertilityClinicsNewHampshire'),
    path('locations/us-regions/fertility-clinics-new-jersey', views.fertilityClinicsNewJersey, name='fertilityClinicsNewJersey'),
    path('locations/us-regions/fertility-clinics-new-mexico', views.fertilityClinicsNewMexico, name='fertilityClinicsNewMexico'),
    path('locations/us-regions/fertility-clinics-new-york', views.fertilityClinicsNewYork, name='fertilityClinicsNewYork'),
    path('locations/us-regions/fertility-clinics-north-carolina', views.fertilityClinicsNorthCarolina, name='fertilityClinicsNorthCarolina'),
    path('locations/us-regions/fertility-clinics-ohio', views.fertilityClinicsOhio, name='fertilityClinicsOhio'),
    path('locations/us-regions/fertility-clinics-oklahoma', views.fertilityClinicsOklahoma, name='fertilityClinicsOklahoma'),
    path('locations/us-regions/fertility-clinics-oregon', views.fertilityClinicsOregon, name='fertilityClinicsOregon'),
    path('locations/us-regions/fertility-clinics-pennsylvania', views.fertilityClinicsPennsylvania, name='fertilityClinicsPennsylvania'),
    path('locations/us-regions/fertility-clinics-rhode-island', views.fertilityClinicsRhodeIsland, name='fertilityClinicsRhodeIsland'),
    path('locations/us-regions/fertility-clinics-south-carolina', views.fertilityClinicsSouthCarolina, name='fertilityClinicsSouthCarolina'),
    path('locations/us-regions/fertility-clinics-south-dakota', views.fertilityClinicsSouthDakota, name='fertilityClinicsSouthDakota'),
    path('locations/us-regions/fertility-clinics-tennessee', views.fertilityClinicsTennessee, name='fertilityClinicsTennessee'),
    path('locations/us-regions/fertility-clinics-texas', views.fertilityClinicsTexas, name='fertilityClinicsTexas'),
    path('locations/us-regions/fertility-clinics-utah', views.fertilityClinicsUtah, name='fertilityClinicsUtah'),
    path('locations/us-regions/fertility-clinics-vermont', views.fertilityClinicsVermont, name='fertilityClinicsVermont'),
    path('locations/us-regions/fertility-clinics-virginia', views.fertilityClinicsVirginia, name='fertilityClinicsVirginia'),
    path('locations/us-regions/fertility-clinics-washington', views.fertilityClinicsWashington, name='fertilityClinicsWashington'),
    path('locations/us-regions/fertility-clinics-west-virginia', views.fertilityClinicsWestVirginia, name='fertilityClinicsWestVirginia'),
    path('locations/us-regions/fertility-clinics-wisconsin', views.fertilityClinicsWisconsin, name='fertilityClinicsWisconsin'),
    path('locations/us-regions/fertility-clinics-wyoming', views.fertilityClinicsWyoming, name='fertilityClinicsWyoming'),
    path('locations/us-regions/fertility-clinics-district-of-columbia', views.fertilityClinicsDistrictOfColumbia, name='fertilityClinicsDistrictOfColumbia'),
]
